addSbtPlugin("com.eed3si9n"              % "sbt-assembly" % "0.14.9")
addSbtPlugin("com.github.gseitz"         % "sbt-release"  % "1.0.11")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "1.1.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.5")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.0.0-RC5")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"      % "0.3.4")
